# -*- coding: utf-8 -*-
"""05_egfr_slope_streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17OxHE--BawY1QAte0Ele1gMNRjCxHjLa

# 📈 Streamlit 기반 eGFR Slope 예측 웹 도구

이 노트북은 학습된 모델(`egfr_slope_model.pkl`)을 기반으로 Streamlit을 통해 예측 웹 도구를 제공합니다.
"""

# Streamlit 웹 예측 도구 (eGFR slope 예측)
import streamlit as st
import joblib
import numpy as np
import shap
import pandas as pd
import matplotlib.pyplot as plt

# 모델 import

# from google.colab import files

print("Please upload the 'egfr_slope_model.pkl' file.")
# uploaded = files.upload()

if 'egfr_slope_model.pkl' in uploaded:
    print("File 'egfr_slope_model.pkl' uploaded successfully.")
else:
    print("Error: 'egfr_slope_model.pkl' not found in uploaded files.")

# 모델 불러오기
# Ensure 'egfr_slope_model.pkl' is uploaded to your Colab environment
model = joblib.load("egfr_slope_model.pkl")

st.title("eGFR Slope 예측 도구 (KNOW-CKD 기반)")
st.markdown("환자의 기초 정보를 입력하면 연간 eGFR 감소 속도를 예측합니다.")

# 사용자 입력 받기
age = st.number_input("나이 (Age)", min_value=18, max_value=100, value=65)
sex = st.selectbox("성별 (Sex)", options=["남", "여"])
bmi = st.number_input("BMI", min_value=10.0, max_value=40.0, value=23.5)
smoking = st.selectbox("흡연 여부", options=["비흡연", "과거흡연", "현재흡연"])
dm = st.selectbox("당뇨병 여부", options=["없음", "있음"])
sbp = st.number_input("수축기 혈압 (SBP)", min_value=80, max_value=200, value=120)
egfr = st.number_input("기저 eGFR", min_value=5.0, max_value=150.0, value=55.0)
alb = st.number_input("Albumin", min_value=1.0, max_value=6.0, value=4.0)
hb = st.number_input("Hemoglobin", min_value=5.0, max_value=20.0, value=12.5)
uacr = st.number_input("UACR", min_value=0.0, max_value=3000.0, value=120.0)
upcr = st.number_input("UPCR", min_value=0.0, max_value=10.0, value=1.2)

# 입력 변수 가공
input_data = pd.DataFrame({
    'Age': [age],
    'Sex': [1 if sex == "남" else 0],
    'BMI': [bmi],
    'Smoking': [0 if smoking == "비흡연" else (1 if smoking == "과거흡연" else 2)],
    'DM': [1 if dm == "있음" else 0],
    'SBP': [sbp],
    'eGFR': [egfr],
    'Alb': [alb],
    'Hb': [hb],
    'UACR': [uacr],
    'UPCR': [upcr]
})

if st.button("예측하기"):
    pred = model.predict(input_data)[0]
    st.success(f"예측된 eGFR 연간 감소 속도: {pred:.2f} mL/min/1.73㎡/year")

    st.markdown("---")
    st.subheader("📊 변수별 영향도 (SHAP)")
    explainer = shap.Explainer(model)
    shap_values = explainer(input_data)

    shap.plots.waterfall(shap_values[0], show=False)
    st.pyplot(bbox_inches='tight')

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
